project:
  type: manuscript

execute:
  freeze: false

toc: false

format:
  html: default
  docx:
    reference-doc: custom-reference-doc.docx
  pdf: default

fig-dpi: 600


bibliography: references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/pnas.csl