channels:
  - conda-forge
  - bioconda
dependencies:
  - _r-mutex=1.0.1
  - aom=3.9.1
  - atk-1.0=2.38.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.34.2
  - ca-certificates=2025.10.5
  - cairo=1.18.0
  - cctools_osx-64=1010.6
  - cffi=1.17.1
  - clang=19.1.3
  - clang-19=19.1.3
  - clang_impl_osx-64=19.1.3
  - clang_osx-64=19.1.3
  - clangxx=19.1.3
  - clangxx_impl_osx-64=19.1.3
  - clangxx_osx-64=19.1.3
  - compiler-rt=19.1.3
  - compiler-rt_osx-64=19.1.3
  - curl=8.10.1
  - dav1d=1.2.1
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - gfortran_impl_osx-64=13.2.0
  - gfortran_osx-64=13.2.0
  - ghostscript=10.04.0
  - giflib=5.2.2
  - glib=2.82.2
  - glib-tools=2.82.2
  - gmp=6.3.0
  - graphite2=1.3.13
  - graphviz=12.0.0
  - gsl=2.7
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=9.0.0
  - icu=75.1
  - imagemagick=7.1.1_39
  - isl=0.26
  - jbig=2.1
  - krb5=1.21.3
  - ld64_osx-64=951.9
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libavif16=1.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.3
  - libcurl=8.10.1
  - libcxx=19.1.3
  - libcxx-devel=19.1.3
  - libde265=1.0.15
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.82.2
  - libheif=1.18.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.3
  - libnghttp2=1.64.0
  - libopenblas=0.3.28
  - libpng=1.6.44
  - librsvg=2.58.4
  - libsqlite=3.47.0
  - libssh2=1.11.0
  - libtiff=4.7.0
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxml2=2.13.4
  - libzlib=1.3.1
  - llvm-openmp=19.1.3
  - llvm-tools=19.1.3
  - llvm-tools-19=19.1.3
  - make=4.4.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - nlopt=2.8.0
  - numpy=2.1.3
  - openjpeg=2.5.2
  - openssl=3.6.0
  - packaging=24.1
  - pandoc=3.5
  - pango=1.54.0
  - pcre2=10.44
  - perl=5.32.1
  - pip=24.3.1
  - pixman=0.43.4
  - pkg-config=0.29.2
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - pthread-stubs=0.4
  - pycparser=2.22
  - pygments=2.18.0
  - python=3.12.7
  - python_abi=3.12
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.84.0_0
  - r-boot=1.3_31
  - r-bootstrap=2019.6
  - r-brew=1.0_10
  - r-broom=1.0.7
  - r-broom.mixed=0.2.9.6
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-car=3.1_3
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-checkmate=2.3.2
  - r-class=7.3_22
  - r-cli=3.6.3
  - r-clock=0.7.1
  - r-cluster=2.1.6
  - r-coda=0.19_4.1
  - r-codetools=0.2_20
  - r-coin=1.4_3
  - r-collections=0.3.7
  - r-colorspace=2.1_1
  - r-commonmark=1.9.2
  - r-conquer=1.3.3
  - r-corrplot=0.95
  - r-cowplot=1.1.3
  - r-cpp11=0.5.0
  - r-crayon=1.5.3
  - r-curl=5.2.1
  - r-cyclocomp=1.1.1
  - r-data.table=1.15.4
  - r-deldir=2.0_4
  - r-deriv=4.1.6
  - r-desc=1.4.3
  - r-diagram=1.6.5
  - r-digest=0.6.37
  - r-doby=4.6.24
  - r-dplyr=1.1.4
  - r-e1071=1.7_16
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.1
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_87
  - r-formula=1.2_5
  - r-fs=1.6.5
  - r-furrr=0.3.1
  - r-future=1.34.0
  - r-future.apply=1.11.2
  - r-generics=0.1.3
  - r-geosphere=1.5_20
  - r-ggfun=0.1.7
  - r-ggh4x=0.2.8
  - r-ggimage=0.3.3
  - r-ggplot2=3.5.1
  - r-ggplotify=0.1.2
  - r-ggpubr=0.6.0
  - r-ggrepel=0.9.6
  - r-ggsci=3.2.0
  - r-ggsignif=0.6.4
  - r-ggtext=0.1.2
  - r-globals=0.16.3
  - r-glue=1.8.0
  - r-gower=1.0.1
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gridtext=0.1.5
  - r-gtable=0.3.6
  - r-hardhat=1.4.0
  - r-highr=0.11
  - r-hmisc=5.2_0
  - r-htmltable=2.4.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpgd=1.3.1
  - r-httr2=1.0.6
  - r-insight=1.2.0
  - r-interp=1.1_6
  - r-ipred=0.9_15
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_10
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9
  - r-kernsmooth=2.23_24
  - r-knitr=1.48
  - r-labeling=0.4.3
  - r-languageserver=0.3.16
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-latticeextra=0.6_30
  - r-lava=1.8.0
  - r-lazyeval=0.2.2
  - r-libcoin=1.0_10
  - r-lifecycle=1.0.4
  - r-lintr=3.1.2
  - r-listenv=0.9.1
  - r-lme4=1.1_35.5
  - r-lmperm=2.1.4
  - r-lmtest=0.9_40
  - r-lubridate=1.9.3
  - r-magick=2.8.5
  - r-magrittr=2.0.3
  - r-markdown=1.13
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-matrixmodels=0.5_3
  - r-matrixstats=1.4.1
  - r-memoise=2.0.1
  - r-mgcv=1.9_1
  - r-microbenchmark=1.5.0
  - r-mime=0.12
  - r-minqa=1.2.8
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-modeltools=0.2_23
  - r-multcomp=1.4_28
  - r-mumin=1.48.4
  - r-munsell=0.5.1
  - r-mvtnorm=1.3_3
  - r-nlme=3.1_165
  - r-nloptr=2.1.1
  - r-nnet=7.3_19
  - r-numderiv=2016.8_1.1
  - r-openssl=2.2.2
  - r-parallelly=1.38.0
  - r-patchwork=1.3.0
  - r-pbkrtest=0.5.3
  - r-perm=1.0_0.4
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.5
  - r-pkgconfig=2.0.3
  - r-pkgload=1.4.0
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polynom=1.4_1
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2024.06.25
  - r-progressr=0.15.0
  - r-proxy=0.4_27
  - r-ps=1.8.1
  - r-purrr=1.0.2
  - r-quantreg=5.99
  - r-r.cache=0.16.0
  - r-r.methodss3=1.8.2
  - r-r.oo=1.27.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.13_1
  - r-rcpparmadillo=14.0.2_1
  - r-rcppeigen=0.3.4.0.2
  - r-recipes=1.1.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-repr=1.1.7
  - r-reshape2=1.4.4
  - r-rex=1.2.1
  - r-rlang=1.1.4
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.2
  - r-rpart=4.1.23
  - r-rprojroot=2.0.4
  - r-rstatix=0.7.2
  - r-rstudioapi=0.17.1
  - r-rsvg=2.6.1
  - r-sandwich=3.1_1
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-shape=1.4.6.1
  - r-sp=2.1_4
  - r-sparsem=1.84_2
  - r-squarem=2021.1
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-styler=1.10.3
  - r-survival=3.7_0
  - r-svglite=2.1.3
  - r-sys=3.4.3
  - r-systemfonts=1.1.0
  - r-th.data=1.1_3
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-timechange=0.3.0
  - r-timedate=4041.110
  - r-tinytex=0.54
  - r-tzdb=0.4.0
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.2
  - r-xfun=0.48
  - r-xml2=1.3.6
  - r-xmlparsedata=1.0.5
  - r-yaml=2.3.10
  - r-yulab.utils=0.1.7
  - r-zoo=1.8_14
  - radian=0.6.13
  - rav1e=0.6.6
  - rchitect=0.4.7
  - readline=8.2
  - setuptools=75.3.0
  - sigtool=0.1.3
  - six=1.16.0
  - svt-av1=2.3.0
  - tapi=1300.6.5
  - tk=8.6.13
  - tktable=2.10
  - tzdata=2024b
  - wcwidth=0.2.13
  - wheel=0.44.0
  - x265=3.5
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-xorgproto=2024.1
  - xz=5.2.6
  - zlib=1.3.1
  - zstd=1.5.6
