name: polyommatini-museum-manuscript

channels:
  - conda-forge
  - bioconda

dependencies:
  - r-base =4.2
  - r-ggplot2
  - r-ggeffects
  - r-svglite
  - r-ggtext
  - r-ggridges
  - r-reshape2
  - r-hmisc
  - r-lme4 =1.1
  - r-lmertest =3.1
  - r-devtools =2.4
  - r-car =3.1
  - r-mumin =1.47
  - r-dplyr =1.1
  - r-ggpubr
  - r-ggpmisc
  - r-geosphere