---
title: "Genetic diversity, inbreeding, and differentiation"
format:
  html:
    code-fold: true
---

```{r}
#| label: load-packages
#| code-summary: Load up required packages and setup species and genome lists

set.seed(20)

library(data.table) # For reading in data while skipping columns
library(stringr) # For separating pop names into regions and sampling years
library(ggplot2) # For plotting
library(ggpubr) # For adding stats to graphs
library(cowplot) # For arranging plots into a multi-panel figure
library(ggtext) # For more control over axis text layout
library(dplyr) # For summarize function and piping
library(geosphere) # For including distances on F~ST~ plot
library(scales) # For some control of plot scales
library(png) # For reading in maps made in QGIS
library(grid) # For plotting maps made in QGIS with ggplot
library(dplyr) # For summary tables in groups
library(nlme) # For mixed effect models
library(broom.mixed) # For tidying mixed effect models
library(Hmisc) # For bootstrapped confidence intervals
library(ggsignif) # For significance levels in plots

species <- c("picarus", "pargus", "csemiargus")
species_names <- c("Po. icarus", "Pl. argus", "Cy. semiargus")
genomes <- c("ilPolIcar1.1", "ilPleArgu1.3", "ilCyaSemi1.1")
```

## Heterozygosity

```{r}
#| label: tbl-heterozygosity

hz_all <- c()

for (i in c(1:length(species))) {
  s <- species[i]
  g <- genomes[i]
  hz <- fread(
    paste0(
      "../analyses/results/datasets/historical-",
      s,
      "-vg-notrans/analyses/heterozygosity/historical-",
      s,
      "-vg-notrans.",
      g,
      "_all.dp6_allsites-filts.filtered_mindp5-allsites-jointcall_allbal0.21-0.79.notrans.fmiss0.3.bcftools.het.tsv"
    ),
    header = TRUE,
    sep = "\t"
  )
  samples <- fread(
    paste0(
      "../analyses/results/datasets/historical-",
      s,
      "-vg-notrans/qc/historical-",
      s,
      "-vg-notrans.",
      g,
      "_all.sampleqc.tsv"
    ),
    header = TRUE,
    sep = "\t",
    select = c("sample", "population", "time")
  )
  hz <- merge(hz, samples, by = "sample")
  hz$species <- s
  hz_all <- rbind(hz_all, hz)
}

hz_all$year <- str_sub(hz_all$population, -4, -1)
hz_all$region <- str_sub(hz_all$population, 1, -5)

hz_all$species <- factor(
  hz_all$species,
  levels = species,
  labels = species_names
)

hz_all$time <- factor(
  hz_all$time,
  levels = c("historical", "modern"),
  labels = c("Historical", "Modern")
)

hz_all$region <- factor(
  hz_all$region,
  levels = c("WSkane", "SWSkane", "ESkane", "SESkane", "NSmaland", "Oland"),
  labels = c(
    "W Skåne", "SW Skåne", "E Skåne", "SE Skåne", "N Småland", "Öland"
  )
)

hz_all$region_group <- hz_all$region
hz_all[hz_all$region_group == "SW Skåne", ]$region_group <- "W Skåne"
hz_all[hz_all$region_group == "SE Skåne", ]$region_group <- "E Skåne"


hz_table <- hz_all[, c(
  "sample", "species", "time", "population", "hetperbp", "hetperalt"
)]

write.table(hz_table, "../tables/hz_ests.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)
```

```{r}
#| label: stats-heterozygosity

hz_means <- hz_all %>%
  group_by(species, population) %>%
  do(
    data.frame(
      rbind(
        Hmisc::smean.cl.boot(.$hetperbp, B = 1000)
      )
    )
  )

write.table(hz_means, "../tables/hz_means.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)

hz_stats <- c()

for (s in species_names) {
  hist <- mean(hz_all[hz_all$species == s & hz_all$time == "Historical", ]$hetperbp * 1000)
  mod <- mean(hz_all[hz_all$species == s & hz_all$time == "Modern", ]$hetperbp * 1000)
  ratio <- mod/hist
  model <- lme(hetperbp * 1000 ~ time, random = ~1|region_group, data = hz_all[hz_all$species == s, ])
  tidyed <- tidy(model, conf.int = TRUE, effects = "fixed")
  tidydf <- tidyed[2, c(3,4,6,7,8,9)]
  tidydf$hist.mean <- hist
  tidydf$mod.mean <- mod
  tidydf$`mod/hist` <- ratio
  tidydf <- round(tidydf, 5)
  tidydf$species <- s
  tidydf <- tidydf[ , c(10, 7, 8, 9, 1, 2, 3, 5, 6, 4)]
  hz_stats <- rbind(hz_stats, tidydf)
}

write.table(hz_stats, "../tables/hz_stats.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)
```

```{r}
#| label: fig-het-box
#| fig-width: 6
#| fig-height: 2.5

hzbox <- ggplot(hz_all, aes(x = time, y = hetperbp * 1000)) +
  facet_grid(cols = vars(species)) +
  geom_boxplot(
    aes(x = time, y = hetperbp * 1000),
    inherit.aes = FALSE,
    outliers = FALSE
  ) +
  geom_point(
    aes(color = region, shape = time),
    position = position_jitterdodge(jitter.width = 0.05)
  ) +
  scale_shape_manual(values = c(17, 16), guide = "none") +
  ylab("<span style='font-size: 9pt'>Heterozygous sites per 1000bp</span><br><span style='font-size: 7pt'>(excl. transitions)</span>") +
  scale_y_continuous(
    labels = number_format(accuracy = 0.1),
    expand = expansion(mult = c(0.05, 0.20))
  ) +
  scale_color_manual(
    values = c("#244F6E", "#244F6E", "#658399", "#658399", "#8A2A3B", "#fecd03"),
    name = "Geographic Region"
  ) +
  geom_signif(
    data = hz_all[hz_all$species == "Cy. semiargus", ],
    comparisons = list(c("Historical", "Modern")),
    annotations="**",
    margin_top = 0,
    y_position = 3
  ) +
  theme_bw() +
  theme(
    legend.position = "none",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_markdown(),
    strip.text.x = element_text(size = 10, face = "italic")
  )
```

## Inbreeding coefficients

```{r}
#| label: froh-table

froh_all <- c()

for (i in c(1:length(species))) {
  s <- species[i]
  g <- genomes[i]
  froh <- fread(
    paste0(
      "../analyses/results/datasets/historical-",
      s,
      "-vg-notrans/plots/inbreeding/historical-",
      s,
      "-vg-notrans.",
      g,
      "_all.dp6_allsites-filts.filtered_mindp5-biallelic-jointcall_allbal0.21-0.79.notrans.fmiss0.3.bcftools.ind_froh.tsv"
    ),
    header = TRUE,
    sep = "\t",
    select = c("sample", "population", "time", "depth", "Froh")
  )
  froh$species <- s
  froh_all <- rbind(froh_all, froh)
}

froh_all <- froh_all[froh_all$sample %in% hz_all$sample, ]

froh_all$year <- str_sub(froh_all$population, -4, -1)
froh_all$region <- str_sub(froh_all$population, 1, -5)

froh_all$species <- factor(
  froh_all$species,
  levels = species,
  labels = c("Po. icarus", "Pl. argus", "Cy. semiargus")
)

froh_all$time <- factor(
  froh_all$time,
  levels = c("historical", "modern"),
  labels = c("Historical", "Modern")
)

froh_all$region <- factor(
  froh_all$region,
  levels = c("WSkane", "SWSkane", "ESkane", "SESkane", "NSmaland", "Oland"),
  labels = c("W Skåne", "SW Skåne", "E Skåne", "SE Skåne", "N Småland", "Öland")
)

froh_all$region_group <- froh_all$region
froh_all[froh_all$region_group == "SW Skåne", ]$region_group <- "W Skåne"
froh_all[froh_all$region_group == "SE Skåne", ]$region_group <- "E Skåne"

froh_table <- froh_all[, c(
  "sample", "species", "time", "population", "Froh"
)]

write.table(froh_table, "../tables/froh_ests.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)
```


```{r}
#| label: stats-froh

froh_means <- froh_all %>%
  group_by(species, population) %>%
  do(
    data.frame(
      rbind(
        Hmisc::smean.cl.boot(.$Froh, B = 1000)
      )
    )
  )

write.table(froh_means, "../tables/froh_means.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)

froh_stats <- c()

for (s in species_names) {
  hist <- mean(froh_all[froh_all$species == s & froh_all$time == "Historical", ]$Froh)
  mod <- mean(froh_all[froh_all$species == s & froh_all$time == "Modern", ]$Froh)
  model <- lme(Froh ~ time, random = ~1|region_group, data = froh_all[froh_all$species == s, ])
  tidyed <- tidy(model, conf.int = TRUE, effects = "fixed")
  tidydf <- tidyed[2, c(3,4,6,7,8,9)]
  tidydf$hist.mean <- hist
  tidydf$mod.mean <- mod
  tidydf <- round(tidydf, 5)
  tidydf$species <- s
  tidydf <- tidydf[ , c(9, 7, 8, 1, 2, 3, 5, 6, 4)]
  froh_stats <- rbind(froh_stats, tidydf)
}

write.table(froh_stats, "../tables/froh_stats.tsv",
  row.names = FALSE, quote = FALSE, sep = "\t"
)
```

```{r}
#| label: fig-froh-box
#| fig-width: 6
#| fig-height: 2.5

frohbox <- ggplot(froh_all, aes(x = time, y = Froh)) +
  facet_grid(cols = vars(species)) +
  geom_boxplot(
    aes(x = time, y = Froh),
    inherit.aes = FALSE,
    outliers = FALSE
  ) +
  geom_point(
    aes(color = region, shape = time),
    position = position_jitterdodge(jitter.width = 0.05)
  ) +
  scale_shape_manual(values = c(17, 16), guide = "none") +
  ylab("<span style='font-size: 9pt'>*F~RoH~* </span><span style='font-size: 7pt'>(*RoH* > 100kb)</span>") +
  scale_color_manual(
    values = c("#244F6E", "#244F6E", "#658399", "#658399", "#8A2A3B", "#fecd03"),
    name = "Geographic Region"
  ) +
  scale_y_continuous(
    labels = number_format(accuracy = 0.1),
    expand = expansion(mult = c(0.05, 0.20))
  ) +
  geom_signif(
    data = froh_all[froh_all$species == "Cy. semiargus", ],
    comparisons = list(c("Historical", "Modern")),
    annotations="**"
  ) +
  theme_bw() +
  theme(
    legend.position = "none",
    panel.grid = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_markdown(),
    strip.text.x = element_text(size = 10, face = "italic")
  )
```

```{r}
#| label: fig-roh-adj-het
#| fig-width: 5
#| fig-height: 7

adj_hz <- merge(froh_all, hz_all)

adj_hz$adj_hz <- adj_hz$hetperbp * 1000 / (1 - adj_hz$Froh)

roh_het <- adj_hz[ , c("sample", "population", "time", "species", "region")]
roh_het2 <- roh_het
roh_het$het <- adj_hz$hetperbp * 1000
roh_het$type <- "Including RoH"
roh_het2$het <- adj_hz$adj_hz
roh_het2$type <- "Excluding RoH"
roh_het <- rbind(roh_het, roh_het2)

roh_het$type <- factor(roh_het$type,
levels = c("Including RoH", "Excluding RoH"))

ggplot(roh_het, aes(x = time, y = het)) +
  facet_grid(rows = vars(species), cols = vars(type), scales = "free_y") +
  geom_boxplot(
    aes(x = time, y = het),
    inherit.aes = FALSE,
    outliers = FALSE
  ) +
  geom_point(
    aes(color = region, shape = time),
    position = position_jitterdodge(jitter.width = 0.05)
  ) +
  scale_shape_manual(values = c(17, 16), guide = "none") +
  ylab("<span style='font-size: 9pt'>Heterozygous sites per 1000bp</span><br><span style='font-size: 7pt'>(excl. transitions)</span>") +
  scale_y_continuous(
    labels = number_format(accuracy = 0.1),
    expand = expansion(mult = c(0.05, 0.20))
  ) +
  scale_color_manual(
    values = c("#244F6E", "#244F6E", "#658399", "#658399", "#8A2A3B", "#fecd03"),
    name = "Geographic Region"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_markdown(),
    strip.text.y = element_text(size = 10, face = "italic")
  )

ggsave("../figures/suppfig-roh-adj-het.png", dpi = 300, create.dir = TRUE)
```

## Nucleotide diversity

```{r}
#| label: tbl-pi
#| eval: true

pi_all <- c()

# read in F_ST results for population pairs
for (i in c(1:length(species))) {
  s <- species[i]
  g <- genomes[i]
  nucdiv <- fread(
    paste0(
      "../analyses/results/datasets/historical-",
      s,
      "-vg-notrans/analyses/pixy/historical-",
      s,
      "-vg-notrans.",
      g,
      "_all.dp6_allsites-filts.filtered_mindp5-allsites-jointcall_allbal0.21-0.79.notrans.fmiss0.3/pixy_pi.txt"
    ),
    header = TRUE,
    sep = "\t",
  )
  nucdiv$species <- s
  pi_all <- rbind(pi_all, nucdiv)
}

# Summarize Fst results per pair
pi_all <- pi_all %>%
  group_by(species, pop) %>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$avg_pi, B = 10000))))

# Read in sampling info, including coordinates
regions <- read.table("../config/pop_groups.tsv", header = TRUE)

# Merge sampling info with F_ST data
pi_all <- merge(pi_all, regions, by.x = "pop", by.y = "population")

pi_all$species <- factor(
  pi_all$species,
  levels = species,
  labels = species_names
)

write.table(pi_all,
  file = "../tables/pi_ests.tsv", sep = "\t",
  quote = FALSE, row.names = FALSE
)
```

## Population differention using *F~ST~*

```{r}
#| label: tbl-fst
#| eval: true

fst_all <- c()

# read in F_ST results for population pairs
for (i in c(1:length(species))) {
  s <- species[i]
  g <- genomes[i]
  fst <- fread(
    paste0(
      "../analyses/results/datasets/historical-",
      s,
      "-vg-notrans/analyses/pixy/historical-",
      s,
      "-vg-notrans.",
      g,
      "_all.dp6_allsites-filts.filtered_mindp5-allsites-jointcall_allbal0.21-0.79.notrans.fmiss0.3/pixy_fst.txt"
    ),
    header = TRUE,
    sep = "\t",
  )
  fst$species <- s
  fst_all <- rbind(fst_all, fst)
}

fst <- fst_all

# Set negative Fst to 0
fst[fst$avg_hudson_fst < 0, ]$avg_hudson_fst <- 0

# Summarize Fst results per pair
fst <- fst %>%
  group_by(species, pop1, pop2) %>%
  do(data.frame(rbind(Hmisc::smean.cl.boot(.$avg_hudson_fst, B = 10000))))

# Read in sampling info, including coordinates
regions <- read.table("../config/pop_groups.tsv", header = TRUE)

# Merge sampling info with F_ST data
fst <- merge(fst, regions, by.x = "pop1", by.y = "population")
fst <- merge(fst, regions, by.x = "pop2", by.y = "population")

# Get rid of pairs within same time period, get pair 'name', and set time
# categories for pair
fst <- fst[abs(fst$year.x - fst$year.y) < 60, ]
fst$pair <- paste0(fst$region.x, "-", fst$region.y)
fst$time <- "placeholder"
fst[fst$year.x < 2000, ]$time <- "historical"
fst[fst$year.x > 2000, ]$time <- "modern"

# Calculate distance between population pairs
fst$dist <- as.vector(
  apply(
    fst[, c("lon.x", "lat.x", "lon.y", "lat.y")], 1, function(x) distm(c(x[1], x[2]), c(x[3], x[4]), fun = distGeo)
  )
)

# Remove pairs where populations contain single samples
fst <- fst[!fst$pop2 %in% c("ESkane1917", "WSkane1943"), ]
fst <- fst[!fst$pop1 %in% c("ESkane1917", "WSkane1943"), ]

# Set up variables for plotting
fst$species <- factor(
  fst$species,
  levels = c("picarus", "pargus", "csemiargus"),
  labels = c("Po. icarus", "Pl. argus", "Cy. semiargus")
)
fst$time <- factor(
  fst$time,
  levels = c("historical", "modern"),
  labels = c("Historical", "Modern")
)

write.table(fst,
  file = "../tables/fst_ests.tsv", sep = "\t",
  quote = FALSE, row.names = FALSE
)
```

```{r}
#| label: fig-fst-box
#| fig-width: 6
#| fig-height: 2.5
#| eval: true

fstplot <- ggplot(
  fst,
  aes(
    x = time,
    y = Mean,
    ymax = Upper,
    ymin = Lower,
    group = pair,
    col = dist / 1000,
    label = paste0(round(dist / 1000, 1), " km")
  )
) +
  geom_line(linewidth = 0.5) +
  geom_point(aes(shape = time), size = 2.5) +
  scale_shape_manual(values = c(17, 16), guide = "none") +
  facet_grid(cols = vars(species)) +
  theme_bw() +
  scale_color_gradient(
    low = "#55AFF4", high = "#132C44",
    name = "Distance (km)"
  ) +
  ylab("<span style='font-size: 9pt'>Hudson *F~ST~*</span>") +
  scale_y_continuous(
    labels = number_format(accuracy = 0.01)
  ) +
  guides(
    colour = guide_colourbar(position = "inside")
  ) +
  theme(
    # legend.background = element_rect(color = "black", size = 0.2),
    legend.title = element_text(size = 8),
    legend.text = element_text(size = 7),
    legend.key.size = unit(0.4, "cm"),
    legend.justification.inside = c(0.02, 0.9),
    axis.title.x = element_blank(),
    panel.grid = element_blank(),
    axis.title.y = element_markdown(),
    strip.text = element_text(face = "italic", size = 10)
  )
```

## Make Figure 1

```{r}
#| label: fig-diversity
#| fig-width: 10.5
#| fig-height: 7
#| eval: true

arrhz <- hzbox

arrfroh <- frohbox

arrfst <- fstplot

map <- readPNG("../resources/gis/sampling_map/historical_map.png")
map <- rasterGrob(map, interpolate = TRUE)
map <- ggplot() +
  geom_blank() +
  annotation_custom(map, xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf) +
  theme(
    panel.background = element_rect(
      fill = "transparent", color = NA
    ),
    plot.background = element_rect(
      fill = "transparent", color = NA
    )
  )

butterflies <- readPNG("../images/butterfly_species_photos.png")
butterflies <- rasterGrob(butterflies, interpolate = TRUE)
butterflies <- ggplot() +
  geom_blank() +
  annotation_custom(
    butterflies,
    xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = Inf
  ) +
  theme(
    panel.background = element_rect(
      fill = "transparent", color = NA
    ),
    plot.background = element_rect(
      fill = "transparent", color = NA
    )
  )

map_photos <- plot_grid(
  butterflies, map,
  labels = c("A", "B"),
  nrow = 2,
  ncol = 1,
  rel_heights = c(0.4, 1)
)

plot_grid(map_photos,
  plot_grid(arrhz, arrfroh, arrfst, ncol = 1, nrow = 3, labels = c("C", "D", "E"), align = "v", axis = "lr"),
  ncol = 2, nrow = 1
) + bgcolor("white")

ggsave("../figures/fig-diversity.png", dpi = 600, create.dir = TRUE)
ggsave("../figures/fig-diversity.svg", dpi = 600, create.dir = TRUE)
```

```{r}
#| label: fig-sims
#| fig-width: 7
#| fig-height: 6

hz_means$year <- str_sub(hz_means$population, -4, -1)
hz_means$region <- str_sub(hz_means$population, 1, -5)
froh_means$year <- str_sub(froh_means$population, -4, -1)
froh_means$region <- str_sub(froh_means$population, 1, -5)

sims <- c()

for (i in 1:length(species)) {
  sn <- species_names[i]
  s <- species[i]
  sdf <- hz_means[hz_means$species == sn, ]
  regs <- unique(sdf$region)
  for (r in regs) {
    if (r == "SESkane") {
    } else if (r == "SWSkane") {
      histh <- sdf[sdf$region == "WSkane" & sdf$year < 2000, ]$Mean
      histy <- sdf[sdf$region == "WSkane" & sdf$year < 2000, ]$year
      modh <- sdf[sdf$region == "SWSkane", ]$Mean
      mody <- sdf[sdf$region == "SWSkane", ]$year
      region <- r
      row <- c(s, sn, region, mody, histy, modh/histh)
      sims <- rbind(sims, row)
    } else if (r == "WSkane" & s == "pargus") {
    } else {
      histh <- sdf[sdf$region == r & sdf$year < 2000, ]$Mean
      histy <- sdf[sdf$region == r & sdf$year < 2000, ]$year
      modh <- sdf[sdf$region == r & sdf$year > 2000, ]$Mean
      mody <- sdf[sdf$region == r & sdf$year > 2000, ]$year
      region <- r
      row <- c(s, sn, region, mody, histy, modh/histh)
      sims <- rbind(sims, row)
    }
  }
}

sims <- data.frame(sims)
colnames(sims) <- c("species", "species_name", "region", "modyear", "histyear", "hetratio")

simdata <- c()

for (i in 1:nrow(sims)) {
  base <- paste(
    sims[i, 1], sims[i, 3], sims[i, 4], sims[i, 5], sep = "-"
  )
  sim <- read.table(
    paste0(
      "../sims/exclfirst/",
      base,
      ".tsv"
    )
  )
  sim$species <- sims[i, 1]
  sim$region <- sims[i, 3]
  sim$hetratio <- sim$V2
  sim$modFroh <- sim$V5
  sim$adjHetRatio <- sim$V3
  simdata <- rbind(simdata, sim[ , c("species", "region", "hetratio", "modFroh", "adjHetRatio")])
}

sims[, "hetratio"] <- as.numeric(sims[, "hetratio"])
sims$species <- sims$species_name

froh_means
froh_mod <- froh_means[froh_means$year > 2000, ]

simdata$species <- factor(
  simdata$species,
  levels = species,
  labels = species_names
)


sims$species <- factor(
  sims$species,
  levels = species_names,
  labels = species_names
)

hetratio <- simdata %>%
  group_by(species, region) %>%
  summarise(
    min = min(hetratio),
    q25 = quantile(hetratio, 0.25),
    q50 = quantile(hetratio, 0.50),
    q75 = quantile(hetratio, 0.75),
    max = max(hetratio)
  )

modFroh <- simdata %>%
  group_by(species, region) %>%
  summarise(
    min = min(modFroh),
    q25 = quantile(modFroh, 0.25),
    q50 = quantile(modFroh, 0.50),
    q75 = quantile(modFroh, 0.75),
    max = max(modFroh)
  )

adjHetRatio <- simdata %>%
  group_by(species, region) %>%
  summarise(
    min = min(adjHetRatio),
    q25 = quantile(adjHetRatio, 0.25),
    q50 = quantile(adjHetRatio, 0.50),
    q75 = quantile(adjHetRatio, 0.75),
    max = max(adjHetRatio)
  )

sims <- sims[sims$region != "SESkane", ]
froh_mod <- froh_mod[froh_mod$region != "SESkane", ]

hetsim <- ggplot(sims, aes(x = region, y = hetratio)) +
  geom_violin(data = simdata) +
  geom_point(color = "red", size = 3) +
  facet_grid(cols = vars(species), scales = "free_x") +
  ylab("Proportion retained heterozygosity") +
  theme_bw() +
  theme(
    strip.text.x = element_text(size = 10, face = "italic"),
    axis.title.x = element_blank()
  )

frohsim <- ggplot(froh_mod, aes(x = region, y = Mean)) +
  geom_violin(data = simdata, aes(y = modFroh)) +
  geom_point(color = "red", size = 3) +
  facet_grid(cols = vars(species), scales = "free_x") +
  ylab("Mean modern *F~RoH~*") +
  theme_bw() +
  theme(
    strip.text.x = element_text(size = 10, face = "italic"),
    axis.title.y = element_markdown(),
    axis.title.x = element_blank()
  )

plot_grid(
  hetsim,
  frohsim,
  ncol = 1
)

ggsave("../figures/suppfig-sims.png", dpi = 600)
```